//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightWeatherMailManager.MMT_Webs_MailManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MMT_Webs_MailManager.MMT_WEBS_MailManagerSoap")]
    public interface MMT_WEBS_MailManagerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSResponse SendSMS(FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSResponse> SendSMSAsync(FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.MMT_Webs_MailManager.SendMailResponse SendMail(FlightWeatherMailManager.MMT_Webs_MailManager.SendMailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.MMT_Webs_MailManager.SendMailResponse> SendMailAsync(FlightWeatherMailManager.MMT_Webs_MailManager.SendMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.MMT_Webs_MailManager.GenerateTemplateResponse GenerateTemplate(FlightWeatherMailManager.MMT_Webs_MailManager.GenerateTemplateRequestObj GenerateTemplateobjRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.MMT_Webs_MailManager.GenerateTemplateResponse> GenerateTemplateAsync(FlightWeatherMailManager.MMT_Webs_MailManager.GenerateTemplateRequestObj GenerateTemplateobjRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSRequestObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime requestDateField;
        
        private string acknowledgementNoField;
        
        private string pNRNoField;
        
        private string refrenceTypeField;
        
        private string[] sMSToField;
        
        private string sMSTriggerField;
        
        private string sMSFromField;
        
        private string lOBField;
        
        private string contactNoField;
        
        private string refrenceNoField;
        
        private string sourceField;
        
        private int dBNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AcknowledgementNo {
            get {
                return this.acknowledgementNoField;
            }
            set {
                this.acknowledgementNoField = value;
                this.RaisePropertyChanged("AcknowledgementNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PNRNo {
            get {
                return this.pNRNoField;
            }
            set {
                this.pNRNoField = value;
                this.RaisePropertyChanged("PNRNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RefrenceType {
            get {
                return this.refrenceTypeField;
            }
            set {
                this.refrenceTypeField = value;
                this.RaisePropertyChanged("RefrenceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public string[] SMSTo {
            get {
                return this.sMSToField;
            }
            set {
                this.sMSToField = value;
                this.RaisePropertyChanged("SMSTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SMSTrigger {
            get {
                return this.sMSTriggerField;
            }
            set {
                this.sMSTriggerField = value;
                this.RaisePropertyChanged("SMSTrigger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SMSFrom {
            get {
                return this.sMSFromField;
            }
            set {
                this.sMSFromField = value;
                this.RaisePropertyChanged("SMSFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LOB {
            get {
                return this.lOBField;
            }
            set {
                this.lOBField = value;
                this.RaisePropertyChanged("LOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
                this.RaisePropertyChanged("ContactNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RefrenceNo {
            get {
                return this.refrenceNoField;
            }
            set {
                this.refrenceNoField = value;
                this.RaisePropertyChanged("RefrenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DBName {
            get {
                return this.dBNameField;
            }
            set {
                this.dBNameField = value;
                this.RaisePropertyChanged("DBName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateTemplateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sendMailResultField;
        
        private string strMailBodyField;
        
        private byte[] pDFBytesField;
        
        private ErrorResponse errorResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool SendMailResult {
            get {
                return this.sendMailResultField;
            }
            set {
                this.sendMailResultField = value;
                this.RaisePropertyChanged("SendMailResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string strMailBody {
            get {
                return this.strMailBodyField;
            }
            set {
                this.strMailBodyField = value;
                this.RaisePropertyChanged("strMailBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] PDFBytes {
            get {
                return this.pDFBytesField;
            }
            set {
                this.pDFBytesField = value;
                this.RaisePropertyChanged("PDFBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ErrorResponse ErrorResponse {
            get {
                return this.errorResponseField;
            }
            set {
                this.errorResponseField = value;
                this.RaisePropertyChanged("ErrorResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateTemplateRequestObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime requestDateField;
        
        private string refrenceTypeField;
        
        private string contactNoField;
        
        private string lOBIDField;
        
        private string refrenceNoField;
        
        private string bodyDocumentField;
        
        private string[] attachmentDocumentField;
        
        private string fromField;
        
        private string toField;
        
        private string ccField;
        
        private string bCCField;
        
        private string subjectField;
        
        private string sourceField;
        
        private GenerateTemplateSendMailEnum sendMailField;
        
        private string dBNameField;
        
        private string inputXMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RefrenceType {
            get {
                return this.refrenceTypeField;
            }
            set {
                this.refrenceTypeField = value;
                this.RaisePropertyChanged("RefrenceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
                this.RaisePropertyChanged("ContactNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LOBID {
            get {
                return this.lOBIDField;
            }
            set {
                this.lOBIDField = value;
                this.RaisePropertyChanged("LOBID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RefrenceNo {
            get {
                return this.refrenceNoField;
            }
            set {
                this.refrenceNoField = value;
                this.RaisePropertyChanged("RefrenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BodyDocument {
            get {
                return this.bodyDocumentField;
            }
            set {
                this.bodyDocumentField = value;
                this.RaisePropertyChanged("BodyDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] AttachmentDocument {
            get {
                return this.attachmentDocumentField;
            }
            set {
                this.attachmentDocumentField = value;
                this.RaisePropertyChanged("AttachmentDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CC {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
                this.RaisePropertyChanged("CC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BCC {
            get {
                return this.bCCField;
            }
            set {
                this.bCCField = value;
                this.RaisePropertyChanged("BCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public GenerateTemplateSendMailEnum SendMail {
            get {
                return this.sendMailField;
            }
            set {
                this.sendMailField = value;
                this.RaisePropertyChanged("SendMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DBName {
            get {
                return this.dBNameField;
            }
            set {
                this.dBNameField = value;
                this.RaisePropertyChanged("DBName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string InputXML {
            get {
                return this.inputXMLField;
            }
            set {
                this.inputXMLField = value;
                this.RaisePropertyChanged("InputXML");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum GenerateTemplateSendMailEnum {
        
        /// <remarks/>
        NoMail,
        
        /// <remarks/>
        AsHTML,
        
        /// <remarks/>
        AsPDF,
        
        /// <remarks/>
        AsBOTH,
        
        /// <remarks/>
        AsMailOnly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TemplateParam : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestObj : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acknowledgementNoField;
        
        private string pNRNoField;
        
        private System.DateTime requestDateField;
        
        private string refrenceTypeField;
        
        private string contactNoField;
        
        private string lOBIDField;
        
        private string refrenceNoField;
        
        private string bodyDocumentField;
        
        private string[] attachmentDocumentField;
        
        private string fromField;
        
        private string toField;
        
        private string ccField;
        
        private string bCCField;
        
        private string subjectField;
        
        private string sourceField;
        
        private SendMailEnum sendMailField;
        
        private TemplateParam[] additionalTemplateParametersField;
        
        private int dBNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AcknowledgementNo {
            get {
                return this.acknowledgementNoField;
            }
            set {
                this.acknowledgementNoField = value;
                this.RaisePropertyChanged("AcknowledgementNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PNRNo {
            get {
                return this.pNRNoField;
            }
            set {
                this.pNRNoField = value;
                this.RaisePropertyChanged("PNRNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RefrenceType {
            get {
                return this.refrenceTypeField;
            }
            set {
                this.refrenceTypeField = value;
                this.RaisePropertyChanged("RefrenceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ContactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
                this.RaisePropertyChanged("ContactNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LOBID {
            get {
                return this.lOBIDField;
            }
            set {
                this.lOBIDField = value;
                this.RaisePropertyChanged("LOBID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RefrenceNo {
            get {
                return this.refrenceNoField;
            }
            set {
                this.refrenceNoField = value;
                this.RaisePropertyChanged("RefrenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BodyDocument {
            get {
                return this.bodyDocumentField;
            }
            set {
                this.bodyDocumentField = value;
                this.RaisePropertyChanged("BodyDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public string[] AttachmentDocument {
            get {
                return this.attachmentDocumentField;
            }
            set {
                this.attachmentDocumentField = value;
                this.RaisePropertyChanged("AttachmentDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CC {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
                this.RaisePropertyChanged("CC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string BCC {
            get {
                return this.bCCField;
            }
            set {
                this.bCCField = value;
                this.RaisePropertyChanged("BCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public SendMailEnum SendMail {
            get {
                return this.sendMailField;
            }
            set {
                this.sendMailField = value;
                this.RaisePropertyChanged("SendMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public TemplateParam[] AdditionalTemplateParameters {
            get {
                return this.additionalTemplateParametersField;
            }
            set {
                this.additionalTemplateParametersField = value;
                this.RaisePropertyChanged("AdditionalTemplateParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int DBName {
            get {
                return this.dBNameField;
            }
            set {
                this.dBNameField = value;
                this.RaisePropertyChanged("DBName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SendMailEnum {
        
        /// <remarks/>
        NoMail,
        
        /// <remarks/>
        AsHTML,
        
        /// <remarks/>
        AsPDF,
        
        /// <remarks/>
        AsBOTH,
        
        /// <remarks/>
        AsMailOnly,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightWeatherMailManager.MMT_Webs_MailManager.SMSRequestObj SMSMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSMSErrorMessage;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(FlightWeatherMailManager.MMT_Webs_MailManager.SMSRequestObj SMSMessage, string strSMSErrorMessage) {
            this.SMSMessage = SMSMessage;
            this.strSMSErrorMessage = strSMSErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strSMSErrorMessage;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(bool SendSMSResult, string strSMSErrorMessage) {
            this.SendSMSResult = SendSMSResult;
            this.strSMSErrorMessage = strSMSErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightWeatherMailManager.MMT_Webs_MailManager.RequestObj MailMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strMailBody;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strErrorMessage;
        
        public SendMailRequest() {
        }
        
        public SendMailRequest(FlightWeatherMailManager.MMT_Webs_MailManager.RequestObj MailMessage, string strMailBody, byte[] Attachment, string strErrorMessage) {
            this.MailMessage = MailMessage;
            this.strMailBody = strMailBody;
            this.Attachment = Attachment;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendMailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strMailBody;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Attachment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strErrorMessage;
        
        public SendMailResponse() {
        }
        
        public SendMailResponse(bool SendMailResult, string strMailBody, byte[] Attachment, string strErrorMessage) {
            this.SendMailResult = SendMailResult;
            this.strMailBody = strMailBody;
            this.Attachment = Attachment;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MMT_WEBS_MailManagerSoapChannel : FlightWeatherMailManager.MMT_Webs_MailManager.MMT_WEBS_MailManagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MMT_WEBS_MailManagerSoapClient : System.ServiceModel.ClientBase<FlightWeatherMailManager.MMT_Webs_MailManager.MMT_WEBS_MailManagerSoap>, FlightWeatherMailManager.MMT_Webs_MailManager.MMT_WEBS_MailManagerSoap {
        
        public MMT_WEBS_MailManagerSoapClient() {
        }
        
        public MMT_WEBS_MailManagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MMT_WEBS_MailManagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MMT_WEBS_MailManagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MMT_WEBS_MailManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSResponse FlightWeatherMailManager.MMT_Webs_MailManager.MMT_WEBS_MailManagerSoap.SendSMS(FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public bool SendSMS(FlightWeatherMailManager.MMT_Webs_MailManager.SMSRequestObj SMSMessage, ref string strSMSErrorMessage) {
            FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSRequest inValue = new FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSRequest();
            inValue.SMSMessage = SMSMessage;
            inValue.strSMSErrorMessage = strSMSErrorMessage;
            FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSResponse retVal = ((FlightWeatherMailManager.MMT_Webs_MailManager.MMT_WEBS_MailManagerSoap)(this)).SendSMS(inValue);
            strSMSErrorMessage = retVal.strSMSErrorMessage;
            return retVal.SendSMSResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSResponse> SendSMSAsync(FlightWeatherMailManager.MMT_Webs_MailManager.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.MMT_Webs_MailManager.SendMailResponse FlightWeatherMailManager.MMT_Webs_MailManager.MMT_WEBS_MailManagerSoap.SendMail(FlightWeatherMailManager.MMT_Webs_MailManager.SendMailRequest request) {
            return base.Channel.SendMail(request);
        }
        
        public bool SendMail(FlightWeatherMailManager.MMT_Webs_MailManager.RequestObj MailMessage, ref string strMailBody, ref byte[] Attachment, ref string strErrorMessage) {
            FlightWeatherMailManager.MMT_Webs_MailManager.SendMailRequest inValue = new FlightWeatherMailManager.MMT_Webs_MailManager.SendMailRequest();
            inValue.MailMessage = MailMessage;
            inValue.strMailBody = strMailBody;
            inValue.Attachment = Attachment;
            inValue.strErrorMessage = strErrorMessage;
            FlightWeatherMailManager.MMT_Webs_MailManager.SendMailResponse retVal = ((FlightWeatherMailManager.MMT_Webs_MailManager.MMT_WEBS_MailManagerSoap)(this)).SendMail(inValue);
            strMailBody = retVal.strMailBody;
            Attachment = retVal.Attachment;
            strErrorMessage = retVal.strErrorMessage;
            return retVal.SendMailResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.MMT_Webs_MailManager.SendMailResponse> SendMailAsync(FlightWeatherMailManager.MMT_Webs_MailManager.SendMailRequest request) {
            return base.Channel.SendMailAsync(request);
        }
        
        public FlightWeatherMailManager.MMT_Webs_MailManager.GenerateTemplateResponse GenerateTemplate(FlightWeatherMailManager.MMT_Webs_MailManager.GenerateTemplateRequestObj GenerateTemplateobjRequest) {
            return base.Channel.GenerateTemplate(GenerateTemplateobjRequest);
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.MMT_Webs_MailManager.GenerateTemplateResponse> GenerateTemplateAsync(FlightWeatherMailManager.MMT_Webs_MailManager.GenerateTemplateRequestObj GenerateTemplateobjRequest) {
            return base.Channel.GenerateTemplateAsync(GenerateTemplateobjRequest);
        }
    }
}
