//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MMTSqlLiveEntities : DbContext
    {
        public MMTSqlLiveEntities()
            : base("name=MMTSqlLiveEntities")
        {
        }
        public MMTSqlLiveEntities(string name)
            : base(name)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_FlightStatusLog> tbl_FlightStatusLog { get; set; }
        public DbSet<tbl_WeatherStatusLog> tbl_WeatherStatusLog { get; set; }
    }
}
