//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Queue
    {
        public byte[] timestamp { get; set; }
        public string Message_ID { get; set; }
        public System.DateTime Request_Date_Time { get; set; }
        public string Sender_Name { get; set; }
        public string Mobile_No_ { get; set; }
        public string Message_Text { get; set; }
        public byte Status { get; set; }
        public string Document_No_ { get; set; }
        public string Trigger_Point { get; set; }
        public byte Schedule_SMS { get; set; }
        public int MSG_Type { get; set; }
        public string LOBID { get; set; }
        public string BodyDocument { get; set; }
        public string AttachmentDocument { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Subject { get; set; }
        public int SendMail { get; set; }
        public string Source { get; set; }
        public string RefrenceType { get; set; }
        public string Acknowledgement_No_ { get; set; }
    }
}
