//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WeatherStatusLog
    {
        public int PKID { get; set; }
        public string AirPortCode { get; set; }
        public Nullable<System.DateTime> WeatherStatusDate { get; set; }
        public string MorningStatus { get; set; }
        public string EveningStatus { get; set; }
        public string CompleteDayStatus { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
    }
}
