//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightWeatherMailManager.InteractionManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InteractionManager.MMT_WEBS_InteractionManagerSoap")]
    public interface MMT_WEBS_InteractionManagerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToSMSQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddToSMSQueueResponse AddToSMSQueue(FlightWeatherMailManager.InteractionManager.AddToSMSQueueRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToSMSQueue", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToSMSQueueResponse> AddToSMSQueueAsync(FlightWeatherMailManager.InteractionManager.AddToSMSQueueRequest request);
        
        // CODEGEN: Parameter 'INTERACTION' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToSMSQueue_v2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Response AddToSMSQueue_v2(FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToSMSQueue_v2", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Response> AddToSMSQueue_v2Async(FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.SendSMSResponse SendSMS(FlightWeatherMailManager.InteractionManager.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.SendSMSResponse> SendSMSAsync(FlightWeatherMailManager.InteractionManager.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSMSSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddSMSSetResponse AddSMSSet(FlightWeatherMailManager.InteractionManager.AddSMSSetRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSMSSet", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddSMSSetResponse> AddSMSSetAsync(FlightWeatherMailManager.InteractionManager.AddSMSSetRequest request);
        
        // CODEGEN: Parameter 'SMSSet' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSMSSet_v2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Response AddSMSSet_v2(FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSMSSet_v2", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Response> AddSMSSet_v2Async(FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.SendSMSSetResponse SendSMSSet(FlightWeatherMailManager.InteractionManager.SendSMSSetRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSSet", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.SendSMSSetResponse> SendSMSSetAsync(FlightWeatherMailManager.InteractionManager.SendSMSSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToSMSQueueString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringResponse AddToSMSQueueString(FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToSMSQueueString", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringResponse> AddToSMSQueueStringAsync(FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToSMSQueueString_v2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.smsError[] AddToSMSQueueString_v2(string strSMSXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToSMSQueueString_v2", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.smsError[]> AddToSMSQueueString_v2Async(string strSMSXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToEmailQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddToEmailQueueResponse AddToEmailQueue(FlightWeatherMailManager.InteractionManager.AddToEmailQueueRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToEmailQueue", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToEmailQueueResponse> AddToEmailQueueAsync(FlightWeatherMailManager.InteractionManager.AddToEmailQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToTransactionLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddToTransactionLogResponse AddToTransactionLog(FlightWeatherMailManager.InteractionManager.AddToTransactionLogRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToTransactionLog", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToTransactionLogResponse> AddToTransactionLogAsync(FlightWeatherMailManager.InteractionManager.AddToTransactionLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToTransactionLogWithRequestResponseTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeResponse AddToTransactionLogWithRequestResponseTime(FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToTransactionLogWithRequestResponseTime", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeResponse> AddToTransactionLogWithRequestResponseTimeAsync(FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToEmailQueueUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateResponse AddToEmailQueueUpdate(FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToEmailQueueUpdate", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateResponse> AddToEmailQueueUpdateAsync(FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FlightWeatherMailManager.InteractionManager.SendEmailResponse SendEmail(FlightWeatherMailManager.InteractionManager.SendEmailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.SendEmailResponse> SendEmailAsync(FlightWeatherMailManager.InteractionManager.SendEmailRequest request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMSQueueV2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSQueue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileNumberField;
        
        private string messageIDField;
        
        private string recipientNameField;
        
        private string messageField;
        
        private string requestDateTimeField;
        
        private string sMSReasonField;
        
        private string isImmediateField;
        
        private string sourceField;
        
        private string uniqueIDField;
        
        private string uniqueIDTypeField;
        
        private string senderNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("MobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecipientName {
            get {
                return this.recipientNameField;
            }
            set {
                this.recipientNameField = value;
                this.RaisePropertyChanged("RecipientName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RequestDateTime {
            get {
                return this.requestDateTimeField;
            }
            set {
                this.requestDateTimeField = value;
                this.RaisePropertyChanged("RequestDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SMSReason {
            get {
                return this.sMSReasonField;
            }
            set {
                this.sMSReasonField = value;
                this.RaisePropertyChanged("SMSReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IsImmediate {
            get {
                return this.isImmediateField;
            }
            set {
                this.isImmediateField = value;
                this.RaisePropertyChanged("IsImmediate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
                this.RaisePropertyChanged("UniqueID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string UniqueIDType {
            get {
                return this.uniqueIDTypeField;
            }
            set {
                this.uniqueIDTypeField = value;
                this.RaisePropertyChanged("UniqueIDType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SenderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
                this.RaisePropertyChanged("SenderName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EMailAttachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentIdField;
        
        private string fileNameField;
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
                this.RaisePropertyChanged("ContentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EMailMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime requestDateField;
        
        private string sourceField;
        
        private string referenceTypeField;
        
        private string referenceNoField;
        
        private string fromField;
        
        private string[] toField;
        
        private string[] ccField;
        
        private string[] bccField;
        
        private string subjectField;
        
        private bool isBodyHtmlField;
        
        private bool isBodyXmlField;
        
        private bool bodyFromFileField;
        
        private string xslUrlField;
        
        private string xslFoUrlField;
        
        private string bodyField;
        
        private System.Xml.XmlNode bodyXmlField;
        
        private EMailAttachment[] attachmentField;
        
        private string[] attachmentFileField;
        
        private EmailType emailTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReferenceType {
            get {
                return this.referenceTypeField;
            }
            set {
                this.referenceTypeField = value;
                this.RaisePropertyChanged("ReferenceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReferenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("ReferenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] CC {
            get {
                return this.ccField;
            }
            set {
                this.ccField = value;
                this.RaisePropertyChanged("CC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] Bcc {
            get {
                return this.bccField;
            }
            set {
                this.bccField = value;
                this.RaisePropertyChanged("Bcc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsBodyHtml {
            get {
                return this.isBodyHtmlField;
            }
            set {
                this.isBodyHtmlField = value;
                this.RaisePropertyChanged("IsBodyHtml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsBodyXml {
            get {
                return this.isBodyXmlField;
            }
            set {
                this.isBodyXmlField = value;
                this.RaisePropertyChanged("IsBodyXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool BodyFromFile {
            get {
                return this.bodyFromFileField;
            }
            set {
                this.bodyFromFileField = value;
                this.RaisePropertyChanged("BodyFromFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string XslUrl {
            get {
                return this.xslUrlField;
            }
            set {
                this.xslUrlField = value;
                this.RaisePropertyChanged("XslUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string XslFoUrl {
            get {
                return this.xslFoUrlField;
            }
            set {
                this.xslFoUrlField = value;
                this.RaisePropertyChanged("XslFoUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.Xml.XmlNode BodyXml {
            get {
                return this.bodyXmlField;
            }
            set {
                this.bodyXmlField = value;
                this.RaisePropertyChanged("BodyXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attachment", Order=16)]
        public EMailAttachment[] Attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
                this.RaisePropertyChanged("Attachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentFile", Order=17)]
        public string[] AttachmentFile {
            get {
                return this.attachmentFileField;
            }
            set {
                this.attachmentFileField = value;
                this.RaisePropertyChanged("AttachmentFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public EmailType emailType {
            get {
                return this.emailTypeField;
            }
            set {
                this.emailTypeField = value;
                this.RaisePropertyChanged("emailType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EmailType {
        
        /// <remarks/>
        General,
        
        /// <remarks/>
        ForgotPassword,
        
        /// <remarks/>
        Eticket,
        
        /// <remarks/>
        UserRegistration,
        
        /// <remarks/>
        MTR,
        
        /// <remarks/>
        HotelVoucher,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailQueue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fromField;
        
        private string recipientNameField;
        
        private string emailToField;
        
        private string emailCCField;
        
        private string emailBCCField;
        
        private string subjectField;
        
        private string bodyFileField;
        
        private string attachmentFileField;
        
        private string isHTMLBodyField;
        
        private string bodyTextField;
        
        private string requestDateTimeField;
        
        private string sourceField;
        
        private string uniqueIDField;
        
        private string uniqueIDTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RecipientName {
            get {
                return this.recipientNameField;
            }
            set {
                this.recipientNameField = value;
                this.RaisePropertyChanged("RecipientName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EmailTo {
            get {
                return this.emailToField;
            }
            set {
                this.emailToField = value;
                this.RaisePropertyChanged("EmailTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmailCC {
            get {
                return this.emailCCField;
            }
            set {
                this.emailCCField = value;
                this.RaisePropertyChanged("EmailCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EmailBCC {
            get {
                return this.emailBCCField;
            }
            set {
                this.emailBCCField = value;
                this.RaisePropertyChanged("EmailBCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BodyFile {
            get {
                return this.bodyFileField;
            }
            set {
                this.bodyFileField = value;
                this.RaisePropertyChanged("BodyFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AttachmentFile {
            get {
                return this.attachmentFileField;
            }
            set {
                this.attachmentFileField = value;
                this.RaisePropertyChanged("AttachmentFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IsHTMLBody {
            get {
                return this.isHTMLBodyField;
            }
            set {
                this.isHTMLBodyField = value;
                this.RaisePropertyChanged("IsHTMLBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BodyText {
            get {
                return this.bodyTextField;
            }
            set {
                this.bodyTextField = value;
                this.RaisePropertyChanged("BodyText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RequestDateTime {
            get {
                return this.requestDateTimeField;
            }
            set {
                this.requestDateTimeField = value;
                this.RaisePropertyChanged("RequestDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("Source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
                this.RaisePropertyChanged("UniqueID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string UniqueIDType {
            get {
                return this.uniqueIDTypeField;
            }
            set {
                this.uniqueIDTypeField = value;
                this.RaisePropertyChanged("UniqueIDType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class smsError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strMessageIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string strMessageID {
            get {
                return this.strMessageIDField;
            }
            set {
                this.strMessageIDField = value;
                this.RaisePropertyChanged("strMessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSQueueV2 : SMSQueue {
        
        private bool updateCRMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool UpdateCRM {
            get {
                return this.updateCRMField;
            }
            set {
                this.updateCRMField = value;
                this.RaisePropertyChanged("UpdateCRM");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToSMSQueue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToSMSQueueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddToSMSQueueRequest() {
        }
        
        public AddToSMSQueueRequest(FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION, string strErrorMessage) {
            this.INTERACTION = INTERACTION;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToSMSQueueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToSMSQueueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddToSMSQueueResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddToSMSQueueResponse() {
        }
        
        public AddToSMSQueueResponse(bool AddToSMSQueueResult, string strErrorMessage) {
            this.AddToSMSQueueResult = AddToSMSQueueResult;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToSMSQueue_v2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToSMSQueue_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION;
        
        public AddToSMSQueue_v2Request() {
        }
        
        public AddToSMSQueue_v2Request(FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION) {
            this.INTERACTION = INTERACTION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToSMSQueue_v2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToSMSQueue_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddToSMSQueue_v2Result;
        
        public AddToSMSQueue_v2Response() {
        }
        
        public AddToSMSQueue_v2Response(string AddToSMSQueue_v2Result) {
            this.AddToSMSQueue_v2Result = AddToSMSQueue_v2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION, string strErrorMessage) {
            this.INTERACTION = INTERACTION;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(bool SendSMSResult, string strErrorMessage) {
            this.SendSMSResult = SendSMSResult;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSMSSet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddSMSSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SMSQueue", IsNullable=false)]
        public FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddSMSSetRequest() {
        }
        
        public AddSMSSetRequest(FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet, string strErrorMessage) {
            this.SMSSet = SMSSet;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSMSSetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddSMSSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddSMSSetResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddSMSSetResponse() {
        }
        
        public AddSMSSetResponse(bool AddSMSSetResult, string strErrorMessage) {
            this.AddSMSSetResult = AddSMSSetResult;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSMSSet_v2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddSMSSet_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SMSQueue", IsNullable=false)]
        public FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet;
        
        public AddSMSSet_v2Request() {
        }
        
        public AddSMSSet_v2Request(FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet) {
            this.SMSSet = SMSSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddSMSSet_v2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddSMSSet_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddSMSSet_v2Result;
        
        public AddSMSSet_v2Response() {
        }
        
        public AddSMSSet_v2Response(string AddSMSSet_v2Result) {
            this.AddSMSSet_v2Result = AddSMSSet_v2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSSet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SMSQueue", IsNullable=false)]
        public FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public SendSMSSetRequest() {
        }
        
        public SendSMSSetRequest(FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet, string strErrorMessage) {
            this.SMSSet = SMSSet;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSSetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendSMSSetResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public SendSMSSetResponse() {
        }
        
        public SendSMSSetResponse(bool SendSMSSetResult, string strErrorMessage) {
            this.SendSMSSetResult = SendSMSSetResult;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToSMSQueueString", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToSMSQueueStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strSMSXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddToSMSQueueStringRequest() {
        }
        
        public AddToSMSQueueStringRequest(string strSMSXML, string strErrorMessage) {
            this.strSMSXML = strSMSXML;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToSMSQueueStringResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToSMSQueueStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddToSMSQueueStringResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddToSMSQueueStringResponse() {
        }
        
        public AddToSMSQueueStringResponse(bool AddToSMSQueueStringResult, string strErrorMessage) {
            this.AddToSMSQueueStringResult = AddToSMSQueueStringResult;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToEmailQueue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToEmailQueueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightWeatherMailManager.InteractionManager.EmailQueue INTERACTION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddToEmailQueueRequest() {
        }
        
        public AddToEmailQueueRequest(FlightWeatherMailManager.InteractionManager.EmailQueue INTERACTION, string strErrorMessage) {
            this.INTERACTION = INTERACTION;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToEmailQueueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToEmailQueueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddToEmailQueueResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddToEmailQueueResponse() {
        }
        
        public AddToEmailQueueResponse(bool AddToEmailQueueResult, string strErrorMessage) {
            this.AddToEmailQueueResult = AddToEmailQueueResult;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToTransactionLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToTransactionLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLRequsetString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strXMLResponseString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strRequestType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strRequestSubType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strUniqueID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strErrorMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strLogType;
        
        public AddToTransactionLogRequest() {
        }
        
        public AddToTransactionLogRequest(string strXMLRequsetString, string strXMLResponseString, string strRequestType, string strRequestSubType, string strUserID, string strUniqueID, string strErrorMessage, string strLogType) {
            this.strXMLRequsetString = strXMLRequsetString;
            this.strXMLResponseString = strXMLResponseString;
            this.strRequestType = strRequestType;
            this.strRequestSubType = strRequestSubType;
            this.strUserID = strUserID;
            this.strUniqueID = strUniqueID;
            this.strErrorMessage = strErrorMessage;
            this.strLogType = strLogType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToTransactionLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToTransactionLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddToTransactionLogResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddToTransactionLogResponse() {
        }
        
        public AddToTransactionLogResponse(bool AddToTransactionLogResult, string strErrorMessage) {
            this.AddToTransactionLogResult = AddToTransactionLogResult;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToTransactionLogWithRequestResponseTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToTransactionLogWithRequestResponseTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strXMLRequsetString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strXMLResponseString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string strRequestType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string strRequestSubType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string strUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string strUniqueID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string strErrorMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string strLogType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public System.DateTime dtRequestDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public System.DateTime dtResponseDatetime;
        
        public AddToTransactionLogWithRequestResponseTimeRequest() {
        }
        
        public AddToTransactionLogWithRequestResponseTimeRequest(string strXMLRequsetString, string strXMLResponseString, string strRequestType, string strRequestSubType, string strUserID, string strUniqueID, string strErrorMessage, string strLogType, System.DateTime dtRequestDatetime, System.DateTime dtResponseDatetime) {
            this.strXMLRequsetString = strXMLRequsetString;
            this.strXMLResponseString = strXMLResponseString;
            this.strRequestType = strRequestType;
            this.strRequestSubType = strRequestSubType;
            this.strUserID = strUserID;
            this.strUniqueID = strUniqueID;
            this.strErrorMessage = strErrorMessage;
            this.strLogType = strLogType;
            this.dtRequestDatetime = dtRequestDatetime;
            this.dtResponseDatetime = dtResponseDatetime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToTransactionLogWithRequestResponseTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToTransactionLogWithRequestResponseTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddToTransactionLogWithRequestResponseTimeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string strErrorMessage;
        
        public AddToTransactionLogWithRequestResponseTimeResponse() {
        }
        
        public AddToTransactionLogWithRequestResponseTimeResponse(bool AddToTransactionLogWithRequestResponseTimeResult, string strErrorMessage) {
            this.AddToTransactionLogWithRequestResponseTimeResult = AddToTransactionLogWithRequestResponseTimeResult;
            this.strErrorMessage = strErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToEmailQueueUpdate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToEmailQueueUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightWeatherMailManager.InteractionManager.EMailMessage MailMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public AddToEmailQueueUpdateRequest() {
        }
        
        public AddToEmailQueueUpdateRequest(FlightWeatherMailManager.InteractionManager.EMailMessage MailMessage, string ErrorMessage) {
            this.MailMessage = MailMessage;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddToEmailQueueUpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddToEmailQueueUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddToEmailQueueUpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public AddToEmailQueueUpdateResponse() {
        }
        
        public AddToEmailQueueUpdateResponse(bool AddToEmailQueueUpdateResult, string ErrorMessage) {
            this.AddToEmailQueueUpdateResult = AddToEmailQueueUpdateResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightWeatherMailManager.InteractionManager.EMailMessage MailMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(FlightWeatherMailManager.InteractionManager.EMailMessage MailMessage, string ErrorMessage) {
            this.MailMessage = MailMessage;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SendEmailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ErrorMessage;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(bool SendEmailResult, string ErrorMessage) {
            this.SendEmailResult = SendEmailResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MMT_WEBS_InteractionManagerSoapChannel : FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MMT_WEBS_InteractionManagerSoapClient : System.ServiceModel.ClientBase<FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap>, FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap {
        
        public MMT_WEBS_InteractionManagerSoapClient() {
        }
        
        public MMT_WEBS_InteractionManagerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MMT_WEBS_InteractionManagerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MMT_WEBS_InteractionManagerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MMT_WEBS_InteractionManagerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddToSMSQueueResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddToSMSQueue(FlightWeatherMailManager.InteractionManager.AddToSMSQueueRequest request) {
            return base.Channel.AddToSMSQueue(request);
        }
        
        public bool AddToSMSQueue(FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION, ref string strErrorMessage) {
            FlightWeatherMailManager.InteractionManager.AddToSMSQueueRequest inValue = new FlightWeatherMailManager.InteractionManager.AddToSMSQueueRequest();
            inValue.INTERACTION = INTERACTION;
            inValue.strErrorMessage = strErrorMessage;
            FlightWeatherMailManager.InteractionManager.AddToSMSQueueResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddToSMSQueue(inValue);
            strErrorMessage = retVal.strErrorMessage;
            return retVal.AddToSMSQueueResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToSMSQueueResponse> AddToSMSQueueAsync(FlightWeatherMailManager.InteractionManager.AddToSMSQueueRequest request) {
            return base.Channel.AddToSMSQueueAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Response FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddToSMSQueue_v2(FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Request request) {
            return base.Channel.AddToSMSQueue_v2(request);
        }
        
        public string AddToSMSQueue_v2(FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION) {
            FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Request inValue = new FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Request();
            inValue.INTERACTION = INTERACTION;
            FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Response retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddToSMSQueue_v2(inValue);
            return retVal.AddToSMSQueue_v2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Response> FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddToSMSQueue_v2Async(FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Request request) {
            return base.Channel.AddToSMSQueue_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Response> AddToSMSQueue_v2Async(FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION) {
            FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Request inValue = new FlightWeatherMailManager.InteractionManager.AddToSMSQueue_v2Request();
            inValue.INTERACTION = INTERACTION;
            return ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddToSMSQueue_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.SendSMSResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.SendSMS(FlightWeatherMailManager.InteractionManager.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public bool SendSMS(FlightWeatherMailManager.InteractionManager.SMSQueue INTERACTION, ref string strErrorMessage) {
            FlightWeatherMailManager.InteractionManager.SendSMSRequest inValue = new FlightWeatherMailManager.InteractionManager.SendSMSRequest();
            inValue.INTERACTION = INTERACTION;
            inValue.strErrorMessage = strErrorMessage;
            FlightWeatherMailManager.InteractionManager.SendSMSResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).SendSMS(inValue);
            strErrorMessage = retVal.strErrorMessage;
            return retVal.SendSMSResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.SendSMSResponse> SendSMSAsync(FlightWeatherMailManager.InteractionManager.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddSMSSetResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddSMSSet(FlightWeatherMailManager.InteractionManager.AddSMSSetRequest request) {
            return base.Channel.AddSMSSet(request);
        }
        
        public bool AddSMSSet(FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet, ref string strErrorMessage) {
            FlightWeatherMailManager.InteractionManager.AddSMSSetRequest inValue = new FlightWeatherMailManager.InteractionManager.AddSMSSetRequest();
            inValue.SMSSet = SMSSet;
            inValue.strErrorMessage = strErrorMessage;
            FlightWeatherMailManager.InteractionManager.AddSMSSetResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddSMSSet(inValue);
            strErrorMessage = retVal.strErrorMessage;
            return retVal.AddSMSSetResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddSMSSetResponse> AddSMSSetAsync(FlightWeatherMailManager.InteractionManager.AddSMSSetRequest request) {
            return base.Channel.AddSMSSetAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Response FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddSMSSet_v2(FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Request request) {
            return base.Channel.AddSMSSet_v2(request);
        }
        
        public string AddSMSSet_v2(FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet) {
            FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Request inValue = new FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Request();
            inValue.SMSSet = SMSSet;
            FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Response retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddSMSSet_v2(inValue);
            return retVal.AddSMSSet_v2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Response> FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddSMSSet_v2Async(FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Request request) {
            return base.Channel.AddSMSSet_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Response> AddSMSSet_v2Async(FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet) {
            FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Request inValue = new FlightWeatherMailManager.InteractionManager.AddSMSSet_v2Request();
            inValue.SMSSet = SMSSet;
            return ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddSMSSet_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.SendSMSSetResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.SendSMSSet(FlightWeatherMailManager.InteractionManager.SendSMSSetRequest request) {
            return base.Channel.SendSMSSet(request);
        }
        
        public bool SendSMSSet(FlightWeatherMailManager.InteractionManager.SMSQueueV2[] SMSSet, ref string strErrorMessage) {
            FlightWeatherMailManager.InteractionManager.SendSMSSetRequest inValue = new FlightWeatherMailManager.InteractionManager.SendSMSSetRequest();
            inValue.SMSSet = SMSSet;
            inValue.strErrorMessage = strErrorMessage;
            FlightWeatherMailManager.InteractionManager.SendSMSSetResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).SendSMSSet(inValue);
            strErrorMessage = retVal.strErrorMessage;
            return retVal.SendSMSSetResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.SendSMSSetResponse> SendSMSSetAsync(FlightWeatherMailManager.InteractionManager.SendSMSSetRequest request) {
            return base.Channel.SendSMSSetAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddToSMSQueueString(FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringRequest request) {
            return base.Channel.AddToSMSQueueString(request);
        }
        
        public bool AddToSMSQueueString(string strSMSXML, ref string strErrorMessage) {
            FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringRequest inValue = new FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringRequest();
            inValue.strSMSXML = strSMSXML;
            inValue.strErrorMessage = strErrorMessage;
            FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddToSMSQueueString(inValue);
            strErrorMessage = retVal.strErrorMessage;
            return retVal.AddToSMSQueueStringResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringResponse> AddToSMSQueueStringAsync(FlightWeatherMailManager.InteractionManager.AddToSMSQueueStringRequest request) {
            return base.Channel.AddToSMSQueueStringAsync(request);
        }
        
        public FlightWeatherMailManager.InteractionManager.smsError[] AddToSMSQueueString_v2(string strSMSXML) {
            return base.Channel.AddToSMSQueueString_v2(strSMSXML);
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.smsError[]> AddToSMSQueueString_v2Async(string strSMSXML) {
            return base.Channel.AddToSMSQueueString_v2Async(strSMSXML);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddToEmailQueueResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddToEmailQueue(FlightWeatherMailManager.InteractionManager.AddToEmailQueueRequest request) {
            return base.Channel.AddToEmailQueue(request);
        }
        
        public bool AddToEmailQueue(FlightWeatherMailManager.InteractionManager.EmailQueue INTERACTION, ref string strErrorMessage) {
            FlightWeatherMailManager.InteractionManager.AddToEmailQueueRequest inValue = new FlightWeatherMailManager.InteractionManager.AddToEmailQueueRequest();
            inValue.INTERACTION = INTERACTION;
            inValue.strErrorMessage = strErrorMessage;
            FlightWeatherMailManager.InteractionManager.AddToEmailQueueResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddToEmailQueue(inValue);
            strErrorMessage = retVal.strErrorMessage;
            return retVal.AddToEmailQueueResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToEmailQueueResponse> AddToEmailQueueAsync(FlightWeatherMailManager.InteractionManager.AddToEmailQueueRequest request) {
            return base.Channel.AddToEmailQueueAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddToTransactionLogResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddToTransactionLog(FlightWeatherMailManager.InteractionManager.AddToTransactionLogRequest request) {
            return base.Channel.AddToTransactionLog(request);
        }
        
        public bool AddToTransactionLog(string strXMLRequsetString, string strXMLResponseString, string strRequestType, string strRequestSubType, string strUserID, string strUniqueID, ref string strErrorMessage, string strLogType) {
            FlightWeatherMailManager.InteractionManager.AddToTransactionLogRequest inValue = new FlightWeatherMailManager.InteractionManager.AddToTransactionLogRequest();
            inValue.strXMLRequsetString = strXMLRequsetString;
            inValue.strXMLResponseString = strXMLResponseString;
            inValue.strRequestType = strRequestType;
            inValue.strRequestSubType = strRequestSubType;
            inValue.strUserID = strUserID;
            inValue.strUniqueID = strUniqueID;
            inValue.strErrorMessage = strErrorMessage;
            inValue.strLogType = strLogType;
            FlightWeatherMailManager.InteractionManager.AddToTransactionLogResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddToTransactionLog(inValue);
            strErrorMessage = retVal.strErrorMessage;
            return retVal.AddToTransactionLogResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToTransactionLogResponse> AddToTransactionLogAsync(FlightWeatherMailManager.InteractionManager.AddToTransactionLogRequest request) {
            return base.Channel.AddToTransactionLogAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddToTransactionLogWithRequestResponseTime(FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeRequest request) {
            return base.Channel.AddToTransactionLogWithRequestResponseTime(request);
        }
        
        public bool AddToTransactionLogWithRequestResponseTime(string strXMLRequsetString, string strXMLResponseString, string strRequestType, string strRequestSubType, string strUserID, string strUniqueID, ref string strErrorMessage, string strLogType, System.DateTime dtRequestDatetime, System.DateTime dtResponseDatetime) {
            FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeRequest inValue = new FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeRequest();
            inValue.strXMLRequsetString = strXMLRequsetString;
            inValue.strXMLResponseString = strXMLResponseString;
            inValue.strRequestType = strRequestType;
            inValue.strRequestSubType = strRequestSubType;
            inValue.strUserID = strUserID;
            inValue.strUniqueID = strUniqueID;
            inValue.strErrorMessage = strErrorMessage;
            inValue.strLogType = strLogType;
            inValue.dtRequestDatetime = dtRequestDatetime;
            inValue.dtResponseDatetime = dtResponseDatetime;
            FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddToTransactionLogWithRequestResponseTime(inValue);
            strErrorMessage = retVal.strErrorMessage;
            return retVal.AddToTransactionLogWithRequestResponseTimeResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeResponse> AddToTransactionLogWithRequestResponseTimeAsync(FlightWeatherMailManager.InteractionManager.AddToTransactionLogWithRequestResponseTimeRequest request) {
            return base.Channel.AddToTransactionLogWithRequestResponseTimeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.AddToEmailQueueUpdate(FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateRequest request) {
            return base.Channel.AddToEmailQueueUpdate(request);
        }
        
        public bool AddToEmailQueueUpdate(FlightWeatherMailManager.InteractionManager.EMailMessage MailMessage, ref string ErrorMessage) {
            FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateRequest inValue = new FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateRequest();
            inValue.MailMessage = MailMessage;
            inValue.ErrorMessage = ErrorMessage;
            FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).AddToEmailQueueUpdate(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.AddToEmailQueueUpdateResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateResponse> AddToEmailQueueUpdateAsync(FlightWeatherMailManager.InteractionManager.AddToEmailQueueUpdateRequest request) {
            return base.Channel.AddToEmailQueueUpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightWeatherMailManager.InteractionManager.SendEmailResponse FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap.SendEmail(FlightWeatherMailManager.InteractionManager.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public bool SendEmail(FlightWeatherMailManager.InteractionManager.EMailMessage MailMessage, ref string ErrorMessage) {
            FlightWeatherMailManager.InteractionManager.SendEmailRequest inValue = new FlightWeatherMailManager.InteractionManager.SendEmailRequest();
            inValue.MailMessage = MailMessage;
            inValue.ErrorMessage = ErrorMessage;
            FlightWeatherMailManager.InteractionManager.SendEmailResponse retVal = ((FlightWeatherMailManager.InteractionManager.MMT_WEBS_InteractionManagerSoap)(this)).SendEmail(inValue);
            ErrorMessage = retVal.ErrorMessage;
            return retVal.SendEmailResult;
        }
        
        public System.Threading.Tasks.Task<FlightWeatherMailManager.InteractionManager.SendEmailResponse> SendEmailAsync(FlightWeatherMailManager.InteractionManager.SendEmailRequest request) {
            return base.Channel.SendEmailAsync(request);
        }
    }
}
